const express = require('express')
const fileUpload = require('express-fileupload')
const authController = require('./../controller/auth/auth.controller')
const productController = require('./../controller/products/addProductController')
const addingClient = require('./../controller/clients/clientsController')
const store = require('./../controller/store/storeController')
const purchaseOrder = require('./../controller/purchaseOrder/purchaseOrderController')
const salesOrder = require('./../controller/salesController/salesController')
const addsellers = require('./../controller/sellers/addsellers.controller')
const router = express.Router()
router.use(fileUpload())

router.route('/open-account').post(authController.createAccount)
router.route('/KYC').post(authController.KYCUpload)
router.route('/auto-login').get(authController.autoLogin)
router.route('/add-product').post(productController.addProduct)
router.route('/existing-products').get(productController.sendingExistingProducts)
router.route('/add-client').post(addingClient.AddClients)
router.route('/add-prices-for-client').post(addingClient.addFixedPricesForClient)
router.route('/add-range-prices-for-client').post(addingClient.addRangePricesForClient)
router.route('/download-quotation').post(addingClient.formationOfQuotation)
router.route('/store-primary').post(store.storePrimarySetup)
router.route('/store-price-setting').post(store.storePricingSetting)
router.route('/my-store').post(store.liveStore)
router.route('/purchase-order-credentials').post(purchaseOrder.purchaseOrderCredentialsSetting)
router.route('/sending-purchase-order-creds').get(purchaseOrder.sendingPurchaseCrenetials)
router.route('/update-purchase-order-credentials').patch(purchaseOrder.updatePurchaseOrderCredentials)
router.route('/adding-purchase-order').post(purchaseOrder.addingPurchaseOrder)
router.route('/purchase_order_history').get(purchaseOrder.sendingAllPurchaseOrderHistory)
router.route('/download-purchase-orders').post(purchaseOrder.downloadPurchaseOrders)
router.route('/adding-sales-order').post(salesOrder.addSalesOrder)
router.route('/previous-sales-order').get(salesOrder.sendingSalesOrderHistory)
router.route('/add-sellers').post(addsellers.addingSeller)
router.route('/all-sellers').get(addsellers.sendingSellersToUI)
router.route('/update-sellers').post(addsellers.updatingSeller)



module.exports = router
